### ISSUE TITLE
[bug] Tensor Parallel for MIstral Nemo

### ISSUE THREAD

**Issue by shruthan** [ServiceNow/Fast-LLM#152]
# 🐞 Describe the Bug

Using tensor parallel in fast llm to train Mistral Nemo 12B on seems to error out. We used the HF Mistral Nemo base checkpoint and specified tensor parallel as 4. We get the following error:
 
```
Global counter mismatch for parameter "layers.1.norm_1.weight" and shard "weights": 20480 != 5120
```
 
Mistral Nemo attention_norm and ffn_norm weights are of dimension 5120, and 20480 = 5120 * 4 (tensor_parallel=4), so it seems like some issue with the splitting of the weights.

# 🔄 Steps to Reproduce

1. **Get the relevant Fast-LLM version**: Commit 016dc5162e54c046826e877b0d43b02d3426c04c
2. Run the attached config. The pretrained model can be replaced by mistralai/Mistral-Nemo-Base-2407 on HuggingFace
```
training:
  train_iters: 20
  logs:
    interval: 5
  validation:
    iterations: 1
    interval: 1000
  checkpoint:
    interval: 10
    keep: 3
  test_iters: 0
  export:  
    format: mistral
    interval: 10
  wandb:  
    project_name: mistral-7b-cpt
    group_name: test
    entity_name: akshaykalkunte
batch:
  micro_batch_size: 1
  sequence_length: 16384
  batch_size: 128
data:
  tokenizer: {}
  fim: {}
  format: file
  path: /mnt/core_llm_large/shruthan/fastllm/data/fast_llm_dataset.json
  split:
    - 0.998
    - 0.002
    - 0.0
optimizer:  
  weight_decay: 0.1
  beta_1: 0.9
  beta_2: 0.95
  learning_rate:  
    base: 1.2e-04
    decay_style: constant
    warmup_iterations: 1000
pretrained:
  format: mistral
  path: /mnt/core_llm_large/jash/experiments/cpt/mistral_nemo/yarn_cpt_2_5_25_lc_only_16k/hf/epoch0
  model_weights: yes  
model:
  base_model:
    transformer:
      use_flash_attention: yes
    cross_entropy_impl: fused
  multi_stage:
    zero_stage: 3
  distributed:
    tensor_parallel: 4
    training_dtype: bf16
    timeout: 3600.0
run:
  experiment_dir: /mnt/core_llm_large/shruthan/fastllm/exp_mc2_16k_3
```

# 🎯 Expected Behavior

Load the model and shard it in a way that is compatible with tensor parallel setting.
