### ISSUE TITLE
[bug] Barrier timeout for large training runs.

### ISSUE THREAD

**Issue by RaymondLi0** [ServiceNow/Fast-LLM#76]
# 🐞 Describe the Bug

When training models on >=10T tokens, the dataset-blending step takes too long and times out. (ex: `ff031424-08d8-45f1-853f-7e9659daee3a`)

For additional reference, training on 2T tokens takes 30 minutes to blend:
```
2024-11-29 20:31:57,635 [Rank 00] Prepared 5000 of 5054 datasets.
2024-11-29 21:01:57,040 [Rank 00] Initializing training state from scratch...
```

# 🔄 Steps to Reproduce

Train a model with 
```
data:
  path:
  - /mnt/datasets/tokenized/Mistral-Nemo-Base-2407/zyda_2_optimal.json
training:
  train_iters: 5000000
batch:
  micro_batch_size: 1
  batch_size: 256
  sequence_length: 8192
```

# 🎯 Expected Behavior

Does not timeout. Blends the datasets and proceeds to training.
